// GENERATED CODE - DO NOT MODIFY BY HAND
// This file will be generated by build_runner
// Run: flutter pub run build_runner build

part of 'flashcard.dart';

Flashcard _$FlashcardFromJson(Map<String, dynamic> json) => Flashcard(
      id: json['id'] as int?,
      kitId: json['kitId'] as int,
      front: json['front'] as String,
      back: json['back'] as String,
      easiness: (json['easiness'] as num?)?.toDouble() ?? 2.5,
      interval: json['interval'] as int? ?? 0,
      repetitions: json['repetitions'] as int? ?? 0,
      dueDate: json['dueDate'] == null
          ? null
          : DateTime.parse(json['dueDate'] as String),
      createdAt: json['createdAt'] == null
          ? null
          : DateTime.parse(json['createdAt'] as String),
      updatedAt: json['updatedAt'] == null
          ? null
          : DateTime.parse(json['updatedAt'] as String),
    );

Map<String, dynamic> _$FlashcardToJson(Flashcard instance) => <String, dynamic>{
      'id': instance.id,
      'kitId': instance.kitId,
      'front': instance.front,
      'back': instance.back,
      'easiness': instance.easiness,
      'interval': instance.interval,
      'repetitions': instance.repetitions,
      'dueDate': instance.dueDate?.toIso8601String(),
      'createdAt': instance.createdAt.toIso8601String(),
      'updatedAt': instance.updatedAt.toIso8601String(),
    };
