// GENERATED CODE - DO NOT MODIFY BY HAND
// This file will be generated by build_runner
// Run: flutter pub run build_runner build

part of 'quiz.dart';

Quiz _$QuizFromJson(Map<String, dynamic> json) => Quiz(
      id: json['id'] as int?,
      kitId: json['kitId'] as int,
      question: json['question'] as String,
      type: $enumDecode(_$QuestionTypeEnumMap, json['type']),
      options: (json['options'] as List<dynamic>).map((e) => e as String).toList(),
      correctAnswer: json['correctAnswer'] as String,
      userAnswer: json['userAnswer'] as String?,
      isCorrect: json['isCorrect'] as bool?,
      createdAt: json['createdAt'] == null
          ? null
          : DateTime.parse(json['createdAt'] as String),
      updatedAt: json['updatedAt'] == null
          ? null
          : DateTime.parse(json['updatedAt'] as String),
    );

Map<String, dynamic> _$QuizToJson(Quiz instance) => <String, dynamic>{
      'id': instance.id,
      'kitId': instance.kitId,
      'question': instance.question,
      'type': _$QuestionTypeEnumMap[instance.type]!,
      'options': instance.options,
      'correctAnswer': instance.correctAnswer,
      'userAnswer': instance.userAnswer,
      'isCorrect': instance.isCorrect,
      'createdAt': instance.createdAt.toIso8601String(),
      'updatedAt': instance.updatedAt.toIso8601String(),
    };

const _$QuestionTypeEnumMap = {
  QuestionType.multipleChoice: 'multipleChoice',
  QuestionType.trueFalse: 'trueFalse',
  QuestionType.shortAnswer: 'shortAnswer',
};

K _$enumDecode<K, V>(Map<K, V> enumValues, Object? source) {
  return enumValues.entries.singleWhere((e) => e.value == source).key;
}
