// GENERATED CODE - DO NOT MODIFY BY HAND
// This file will be generated by build_runner
// Run: flutter pub run build_runner build

part of 'study_kit.dart';

StudyKit _$StudyKitFromJson(Map<String, dynamic> json) => StudyKit(
      id: json['id'] as int?,
      title: json['title'] as String,
      description: json['description'] as String?,
      summary: json['summary'] as String?,
      sourceType: json['sourceType'] as String,
      filePath: json['filePath'] as String?,
      content: json['content'] as String?,
      flashcardCount: json['flashcardCount'] as int? ?? 0,
      quizCount: json['quizCount'] as int? ?? 0,
      createdAt: json['createdAt'] == null
          ? null
          : DateTime.parse(json['createdAt'] as String),
      updatedAt: json['updatedAt'] == null
          ? null
          : DateTime.parse(json['updatedAt'] as String),
    );

Map<String, dynamic> _$StudyKitToJson(StudyKit instance) => <String, dynamic>{
      'id': instance.id,
      'title': instance.title,
      'description': instance.description,
      'summary': instance.summary,
      'sourceType': instance.sourceType,
      'filePath': instance.filePath,
      'content': instance.content,
      'flashcardCount': instance.flashcardCount,
      'quizCount': instance.quizCount,
      'createdAt': instance.createdAt.toIso8601String(),
      'updatedAt': instance.updatedAt.toIso8601String(),
    };
